version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: reservify
    environment:
      POSTGRES_DB: reservify
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
