// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package bridge

import (
	"time"

	"github.com/google/uuid"
)

type Image struct {
	IDRoom    uuid.UUID
	ImageUrl  string
	Thumbnail bool
}

type Reservation struct {
	ID        uuid.UUID
	IDUser    uuid.UUID
	IDRoom    uuid.UUID
	CheckIn   string
	CheckOut  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Room struct {
	ID          uuid.UUID
	Cod         string
	Name        string
	Description string
	Number      int32
	Vacancies   int32
	Price       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID          uuid.UUID
	Name        string
	Cpf         string
	Email       string
	Phone       string
	DateOfBirth string
	Password    string
	Admin       bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
