// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package bridge

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Reservation struct {
	ID        uuid.UUID
	IDUser    uuid.UUID
	IDRoom    uuid.UUID
	CheckIn   time.Time
	CheckOut  time.Time
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type Room struct {
	ID        uuid.UUID
	Cod       string
	Number    string
	Vacancies int32
	Price     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID          uuid.UUID
	Name        string
	Cpf         string
	Email       string
	Phone       string
	DateOfBirth time.Time
	Password    string
	Admin       bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
