// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: room.sql

package bridge

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createRoom = `-- name: CreateRoom :exec

INSERT INTO room (id, name, description, cod, number, vacancies, price, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateRoomParams struct {
	ID          uuid.UUID
	Name        string
	Description string
	Cod         string
	Number      int32
	Vacancies   int32
	Price       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.ExecContext(ctx, createRoom,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Cod,
		arg.Number,
		arg.Vacancies,
		arg.Price,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteRoomById = `-- name: DeleteRoomById :exec

DELETE FROM room WHERE id = $1
`

func (q *Queries) DeleteRoomById(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteRoomById, id)
	return err
}

const findRoomByCod = `-- name: FindRoomByCod :one

SELECT id, name, description, cod, number, vacancies, price, created_at, updated_at FROM room WHERE cod = $1
`

type FindRoomByCodRow struct {
	ID          uuid.UUID
	Name        string
	Description string
	Cod         string
	Number      int32
	Vacancies   int32
	Price       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) FindRoomByCod(ctx context.Context, cod string) (FindRoomByCodRow, error) {
	row := q.db.QueryRowContext(ctx, findRoomByCod, cod)
	var i FindRoomByCodRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Cod,
		&i.Number,
		&i.Vacancies,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findRoomById = `-- name: FindRoomById :one

SELECT id, name, description, cod, number, vacancies, price, created_at, updated_at FROM room WHERE id = $1
`

type FindRoomByIdRow struct {
	ID          uuid.UUID
	Name        string
	Description string
	Cod         string
	Number      int32
	Vacancies   int32
	Price       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) FindRoomById(ctx context.Context, id uuid.UUID) (FindRoomByIdRow, error) {
	row := q.db.QueryRowContext(ctx, findRoomById, id)
	var i FindRoomByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Cod,
		&i.Number,
		&i.Vacancies,
		&i.Price,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllRooms = `-- name: ListAllRooms :many

SELECT id, name, description, cod, number, vacancies, price, created_at, updated_at FROM room ORDER BY created_at DESC
`

type ListAllRoomsRow struct {
	ID          uuid.UUID
	Name        string
	Description string
	Cod         string
	Number      int32
	Vacancies   int32
	Price       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) ListAllRooms(ctx context.Context) ([]ListAllRoomsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllRooms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllRoomsRow
	for rows.Next() {
		var i ListAllRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Cod,
			&i.Number,
			&i.Vacancies,
			&i.Price,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
