CREATE TABLE IF NOT EXISTS room (
    id UUID PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    cod VARCHAR(255) NOT NULL UNIQUE,
    number INTEGER NOT NULL,
    vacancies INTEGER NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);